# Generated by Django 2.2.10 on 2021-06-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('hash_value', models.CharField(max_length=32)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.File')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
