# Generated by Django 2.2.10 on 2021-06-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
                ('hash_value', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
