# Generated by Django 2.2.10 on 2021-06-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_currentfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentFile',
        ),
    ]
