# Generated by Django 2.2.10 on 2021-06-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210626_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfile',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.File'),
        ),
    ]
